# -*- coding: utf-8 -*-
"""HandWrittenDigitClassification_Lenet5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXySG1v-rqWjd50A3CvWZav4Vt5vU0Jl
"""

# Commented out IPython magic to ensure Python compatibility.
import idx2numpy
import numpy as np
import keras
from keras import layers
from keras.layers import Input, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D
from keras.layers import AveragePooling2D, MaxPooling2D, Dropout, GlobalMaxPooling2D, GlobalAveragePooling2D
from keras.models import Model
from keras.preprocessing import image
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
import pydot
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model

import keras.backend as K
K.set_image_data_format('channels_last')

import scipy.misc
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

# %matplotlib inline

# Loading data from idx files to numpy arrays.
X_train = idx2numpy.convert_from_file('datasets/train-images.idx3-ubyte')
Y_train = idx2numpy.convert_from_file('datasets/train-labels.idx1-ubyte')
X_test =  idx2numpy.convert_from_file('datasets/t10k-images.idx3-ubyte')
Y_test = idx2numpy.convert_from_file('datasets/t10k-labels.idx1-ubyte')

# Normalize image vectors
X_train = X_train/255.
X_test = X_test/255.

# Reshape
X_train = X_train.reshape((X_train.shape[0],X_train.shape[1],X_train.shape[2],1))
X_test = X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1))
Y_train = Y_train.T
Y_test = Y_test.T
Y_train = Y_train.reshape((Y_train.shape[0],1))
Y_test = Y_test.reshape((Y_test.shape[0],1))

print ("number of training examples = " + str(X_train.shape[0]))
print ("number of test examples = " + str(X_test.shape[0]))
print ("X_train shape: " + str(X_train.shape))
print ("Y_train shape: " + str(Y_train.shape))
print ("X_test shape: " + str(X_test.shape))
print ("Y_test shape: " + str(Y_test.shape))

def DigitRecogModel(input_shape):
   X_input = Input(input_shape)
   X = ZeroPadding2D((2, 2))(X_input)

   X = Conv2D(6, (5, 5), strides = (1, 1), name = 'conv0')(X)
   X = BatchNormalization(axis = 3, name = 'bn0')(X)
   X = Activation('relu')(X)
   X = MaxPooling2D(pool_size=2, padding='valid')(X)

   X = Conv2D(16, (5, 5), strides = (1, 1), name = 'conv1')(X)
   X = MaxPooling2D(pool_size=2, padding='valid')(X)

   X = Flatten()(X)
   X = Dense(120, activation='relu', name='fc1')(X)
   X = Dense(84, activation='relu', name='fc2')(X)
   X = Dense(84, activation='relu', name='fc3')(X)
   X = Dense(1, activation='relu', name='fc4')(X)

   model = Model(inputs = X_input, outputs = X, name='DigitRecogModel_Lenet5')

   return model

MyModel = DigitRecogModel(X_train.shape[1:])

MyModel.compile(optimizer = "adam", loss = "mean_squared_error", metrics = ["accuracy"])

MyModel.fit(x = X_train, y = Y_train, epochs = 60, batch_size = 1000)

preds = MyModel.evaluate(x = X_test, y = Y_test)

print()
print ("Loss = " + str(preds[0]))
print ("Test Accuracy = " + str(preds[1]))

MyModel.summary()

plot_model(MyModel, to_file='MyModel.png')
SVG(model_to_dot(MyModel).create(prog='dot', format='svg'))

img_path = 'images/my_image.jpg'
img = image.load_img(img_path, grayscale=True,target_size=(28, 28))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = x/255.0
print('Input image shape:', x.shape)
imgplot = imshow(img)
print(MyModel.predict(x))

